Add tag mention in FAQ
tchapgouv/tchap-landing-page pull request #155
Opened 2023-01-26 09:35 UTC by aulamber

2023-01-27 09:02 UTC, areox-net commented
Meme commentaire que ici https://github.com/tchapgouv/tchap-landing-page/pull/143#issuecomment-1406201634

2023-02-01 15:19 UTC, aulamber commented
@areox-net 
Changé le badge également, tu me diras si c'est bon pour toi et que je peux merger ? Merci :)

2023-02-01 15:55 UTC, areox-net approved these changes

2023-02-02 08:35 UTC, odelcroi commented
Désolé, il y a une erreur sur le ticket, c'est disponible uniquement sur Android ^^

2023-02-02 08:36 UTC, odelcroi requested changes
Désolé, il y a une erreur sur le ticket, c'est disponible uniquement sur Android ^^

2023-02-02 09:07 UTC, aulamber commented
> Désolé, il y a une erreur sur le ticket, c'est disponible uniquement sur Android ^^

Ok, je fais la modif ;)

2023-02-03 12:57 UTC, odelcroi approved these changes

2023-02-03 12:58 UTC, merged