Show csv invitation in faq only on mobiles
tchapgouv/tchap-landing-page pull request #158
Opened 2023-01-30 16:15 UTC by aulamber

In FAQ, web users can no longer invite several members at once by importing .txt of .csv files. This PR variabilize the answer by adding tabs for web and mobile options for this question. Only the mobile option now shows the csv info.
Cf. https://github.com/tchapgouv/tchap-landing-page/issues/154

<img width="1161" alt="Screenshot 2023-01-30 at 17 10 29" src="https://user-images.githubusercontent.com/6305268/215531215-182d5e6d-7d01-4b72-857f-f84e1788b978.png">
<img width="1161" alt="Screenshot 2023-01-30 at 17 10 35" src="https://user-images.githubusercontent.com/6305268/215531243-f2f9302d-e73d-4e9a-9bf4-bd431ea435a3.png">

2023-01-30 16:46 UTC, areox-net commented
The internal tabs work pretty well. However on Chrome Mac the text doesn't take 100% width. This probably due to the old columns class we used in the previous version. `class="MuiGrid-grid-xl-6"` 

![Screenshot 2023-01-30 at 17 42 34](https://user-images.githubusercontent.com/1255251/215540002-a3c7d581-a782-4bf0-b32b-74ac8a249ab8.png)

<img width="530" alt="Screenshot 2023-01-30 at 17 44 50" src="https://user-images.githubusercontent.com/1255251/215540219-e7d805b1-a380-4f0d-bc2a-03b7f81e3108.png">

2023-01-31 08:03 UTC, odelcroi commented
Thanks for the contribution, it looks very nice 👍 

Btw, i've checked on iPhone, i'm not sure mobile clients provides the csv option. In which case, all three clients should have the same answer. To be double checked on Android

2023-01-31 08:54 UTC, areox-net approved these changes
Top!

2023-01-31 09:51 UTC, odelcroi requested changes
make sure this PR is required

2023-01-31 09:57 UTC, aulamber commented
> make sure this PR is required

What do you mean by required? That the need to merge it is real, by asking the design team?

2023-02-01 07:41 UTC, odelcroi commented
Sorry I meant, let's see if this PR is needed

On Tue, Jan 31, 2023 at 10:58 AM Audrey Lambert ***@***.***>
wrote:

> make sure this PR is required
>
> What do you mean by required? That the need to merge it is real, by asking
> the design team?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tchapgouv/tchap-landing-page/pull/158#issuecomment-1410069070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7DRIPF37NM5PQYSGJKGA3WVDO27ANCNFSM6AAAAAAULLB2XM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-02-01 14:25 UTC, closed without merging